alias pi='ssh pi@nextdnspi.local'
alias fr='free -h'
alias ls='ls -hN --color=auto --group-directories-first'
alias la='ls -lah --color=auto --group-directories-first'
alias rm='rm -vi'
alias cp='cp -vi'
alias mv='mv -vi'
alias mkdir='mkdir -pv'
alias distug='distrobox upgrade --all'

